import { Action } from './types'
export const _StartUp = {
  type: Action.Type.ParallelAction,
  presenter: 'LegoWorldPresenter',
  name: '_StartUp',
  siFile: 'elevbott',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Object:ElevatorBottom, World:IELEV',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Background_Bitmap',
      siFile: 'elevbott',
      id: 4,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 10.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\backgrnd.bmp',
      fileType: 1280594720,
      extra: 'World:current',
      children: [],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'LeftArrow_Ctl',
      siFile: 'elevbott',
      id: 1,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Up_Bitmap',
          siFile: 'elevbott',
          id: 5,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [6.0, 109.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowL.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Down_Bitmap',
          siFile: 'elevbott',
          id: 6,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [6.0, 109.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowLon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'RightArrow_Ctl',
      siFile: 'elevbott',
      id: 2,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Up_Bitmap',
          siFile: 'elevbott',
          id: 7,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [575.0, 109.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowR.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Down_Bitmap',
          siFile: 'elevbott',
          id: 8,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [575.0, 109.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowRon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'ElevBott_Elevator_Ctl',
      siFile: 'elevbott',
      id: 3,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Elevator_Mask_Bitmap',
          siFile: 'elevbott',
          id: 9,
          flags: 34,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [288.0, 97.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\ElevMask.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ObjectAction,
      presenter: 'LegoAnimPresenter',
      name: 'ConfigAnimation',
      siFile: 'elevbott',
      id: 10,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\lego\\Media\\ani\\Worlds\\elevmain.ani',
      fileType: 1245859616,
      extra: null,
      children: [],
    },
  ],
} as const
export const LeftArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'LeftArrow_Ctl',
  siFile: 'elevbott',
  id: 1,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Up_Bitmap',
      siFile: 'elevbott',
      id: 5,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [6.0, 109.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowL.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Down_Bitmap',
      siFile: 'elevbott',
      id: 6,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [6.0, 109.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowLon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const RightArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'RightArrow_Ctl',
  siFile: 'elevbott',
  id: 2,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Up_Bitmap',
      siFile: 'elevbott',
      id: 7,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [575.0, 109.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowR.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Down_Bitmap',
      siFile: 'elevbott',
      id: 8,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [575.0, 109.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowRon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const ElevBott_Elevator_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'ElevBott_Elevator_Ctl',
  siFile: 'elevbott',
  id: 3,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Elevator_Mask_Bitmap',
      siFile: 'elevbott',
      id: 9,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [288.0, 97.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\ElevMask.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const Background_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Background_Bitmap',
  siFile: 'elevbott',
  id: 4,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 10.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\backgrnd.bmp',
  fileType: 1280594720,
  extra: 'World:current',
  children: [],
} as const
export const LeftArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Up_Bitmap',
  siFile: 'elevbott',
  id: 5,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [6.0, 109.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowL.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const LeftArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Down_Bitmap',
  siFile: 'elevbott',
  id: 6,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [6.0, 109.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowLon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Up_Bitmap',
  siFile: 'elevbott',
  id: 7,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [575.0, 109.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowR.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Down_Bitmap',
  siFile: 'elevbott',
  id: 8,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [575.0, 109.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\arrowRon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const Elevator_Mask_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Elevator_Mask_Bitmap',
  siFile: 'elevbott',
  id: 9,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [288.0, 97.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Elevator\\ElevMask.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const ConfigAnimation = {
  type: Action.Type.ObjectAction,
  presenter: 'LegoAnimPresenter',
  name: 'ConfigAnimation',
  siFile: 'elevbott',
  id: 10,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\lego\\Media\\ani\\Worlds\\elevmain.ani',
  fileType: 1245859616,
  extra: null,
  children: [],
} as const
export const iica31in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iica31in_PlayWav',
  siFile: 'elevbott',
  id: 500,
  flags: 34,
  startTime: 0,
  duration: 4638,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iica31in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
