import { Action } from './types'
export const _StartUp = {
  type: Action.Type.SerialAction,
  presenter: 'LegoWorldPresenter',
  name: '_StartUp',
  siFile: 'histbook',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Object:HistoryBook, World:IREG',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'ScoreBox',
      siFile: 'histbook',
      id: 1,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\ScoreBox.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 26,
        height: 26,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Background_Bitmap',
      siFile: 'histbook',
      id: 2,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 10.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\Bookgrnd.bmp',
      fileType: 1280594720,
      extra: 'World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 640,
        height: 480,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'A_Bitmap',
      siFile: 'histbook',
      id: 3,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\A.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'B_Bitmap',
      siFile: 'histbook',
      id: 4,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\B.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'C_Bitmap',
      siFile: 'histbook',
      id: 5,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\C.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'D_Bitmap',
      siFile: 'histbook',
      id: 6,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\D.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'E_Bitmap',
      siFile: 'histbook',
      id: 7,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\E.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'F_Bitmap',
      siFile: 'histbook',
      id: 8,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\F.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'G_Bitmap',
      siFile: 'histbook',
      id: 9,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\G.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'H_Bitmap',
      siFile: 'histbook',
      id: 10,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\H.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'I_Bitmap',
      siFile: 'histbook',
      id: 11,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\I.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'J_Bitmap',
      siFile: 'histbook',
      id: 12,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\J.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'K_Bitmap',
      siFile: 'histbook',
      id: 13,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\K.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'L_Bitmap',
      siFile: 'histbook',
      id: 14,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\L.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'M_Bitmap',
      siFile: 'histbook',
      id: 15,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\M.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'N_Bitmap',
      siFile: 'histbook',
      id: 16,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\N.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'O_Bitmap',
      siFile: 'histbook',
      id: 17,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\O.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'P_Bitmap',
      siFile: 'histbook',
      id: 18,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\P.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Q_Bitmap',
      siFile: 'histbook',
      id: 19,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Q.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'R_Bitmap',
      siFile: 'histbook',
      id: 20,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\R.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'S_Bitmap',
      siFile: 'histbook',
      id: 21,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\S.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'T_Bitmap',
      siFile: 'histbook',
      id: 22,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\T.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'U_Bitmap',
      siFile: 'histbook',
      id: 23,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\U.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'V_Bitmap',
      siFile: 'histbook',
      id: 24,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\V.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'W_Bitmap',
      siFile: 'histbook',
      id: 25,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\W.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'X_Bitmap',
      siFile: 'histbook',
      id: 26,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\X.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Y_Bitmap',
      siFile: 'histbook',
      id: 27,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Y.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Z_Bitmap',
      siFile: 'histbook',
      id: 28,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Z.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
      dimensions: {
        width: 24,
        height: 27,
      },
      children: [],
    },
  ],
} as const
export const ScoreBox = {
  type: Action.Type.Still,
  presenter: null,
  name: 'ScoreBox',
  siFile: 'histbook',
  id: 1,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\ScoreBox.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 26,
    height: 26,
  },
  children: [],
} as const
export const Background_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Background_Bitmap',
  siFile: 'histbook',
  id: 2,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 10.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\Bookgrnd.bmp',
  fileType: 1280594720,
  extra: 'World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 640,
    height: 480,
  },
  children: [],
} as const
export const A_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'A_Bitmap',
  siFile: 'histbook',
  id: 3,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\A.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const B_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'B_Bitmap',
  siFile: 'histbook',
  id: 4,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\B.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const C_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'C_Bitmap',
  siFile: 'histbook',
  id: 5,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\C.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const D_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'D_Bitmap',
  siFile: 'histbook',
  id: 6,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\D.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const E_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'E_Bitmap',
  siFile: 'histbook',
  id: 7,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\E.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const F_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'F_Bitmap',
  siFile: 'histbook',
  id: 8,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\F.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const G_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'G_Bitmap',
  siFile: 'histbook',
  id: 9,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\G.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const H_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'H_Bitmap',
  siFile: 'histbook',
  id: 10,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\H.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const I_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'I_Bitmap',
  siFile: 'histbook',
  id: 11,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\I.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const J_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'J_Bitmap',
  siFile: 'histbook',
  id: 12,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\J.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const K_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'K_Bitmap',
  siFile: 'histbook',
  id: 13,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\K.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const L_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'L_Bitmap',
  siFile: 'histbook',
  id: 14,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\L.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const M_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'M_Bitmap',
  siFile: 'histbook',
  id: 15,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\M.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const N_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'N_Bitmap',
  siFile: 'histbook',
  id: 16,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\N.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const O_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'O_Bitmap',
  siFile: 'histbook',
  id: 17,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\O.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const P_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'P_Bitmap',
  siFile: 'histbook',
  id: 18,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\P.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const Q_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Q_Bitmap',
  siFile: 'histbook',
  id: 19,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Q.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const R_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'R_Bitmap',
  siFile: 'histbook',
  id: 20,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\R.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const S_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'S_Bitmap',
  siFile: 'histbook',
  id: 21,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\S.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const T_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'T_Bitmap',
  siFile: 'histbook',
  id: 22,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\T.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const U_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'U_Bitmap',
  siFile: 'histbook',
  id: 23,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\U.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const V_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'V_Bitmap',
  siFile: 'histbook',
  id: 24,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\V.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const W_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'W_Bitmap',
  siFile: 'histbook',
  id: 25,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\W.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const X_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'X_Bitmap',
  siFile: 'histbook',
  id: 26,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\X.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const Y_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Y_Bitmap',
  siFile: 'histbook',
  id: 27,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Y.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
export const Z_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Z_Bitmap',
  siFile: 'histbook',
  id: 28,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Register\\Z.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP, Visibility:FALSE, World:\\lego\\scripts\\infocntr\\histbook;0',
  dimensions: {
    width: 24,
    height: 27,
  },
  children: [],
} as const
