import { Action } from './types'
export const _StartUp = {
  type: Action.Type.ParallelAction,
  presenter: 'LegoWorldPresenter',
  name: '_StartUp',
  siFile: 'infodoor',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Object:InfocenterDoor, World:IISLE',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Background_Bitmap',
      siFile: 'infodoor',
      id: 5,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 10.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\backgrnd.bmp',
      fileType: 1280594720,
      extra: 'World:current',
      children: [],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'LeftArrow_Ctl',
      siFile: 'infodoor',
      id: 1,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Up_Bitmap',
          siFile: 'infodoor',
          id: 6,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [14.0, 150.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowL.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Down_Bitmap',
          siFile: 'infodoor',
          id: 7,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [14.0, 150.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowLon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'RightArrow_Ctl',
      siFile: 'infodoor',
      id: 2,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Up_Bitmap',
          siFile: 'infodoor',
          id: 8,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [581.0, 150.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowR.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Down_Bitmap',
          siFile: 'infodoor',
          id: 9,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [581.0, 150.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowRon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Info_Ctl',
      siFile: 'infodoor',
      id: 3,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Info_Up_Bitmap',
          siFile: 'infodoor',
          id: 10,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [303.0, 108.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Info.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Info_Down_Bitmap',
          siFile: 'infodoor',
          id: 11,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [303.0, 108.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Infos.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Door_Ctl',
      siFile: 'infodoor',
      id: 4,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Door_Up_Bitmap',
          siFile: 'infodoor',
          id: 12,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [227.0, 142.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Door.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ObjectAction,
      presenter: 'LegoAnimPresenter',
      name: 'ConfigAnimation',
      siFile: 'infodoor',
      id: 13,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\lego\\Media\\ani\\Worlds\\exitmain.ani',
      fileType: 1245859616,
      extra: null,
      children: [],
    },
  ],
} as const
export const LeftArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'LeftArrow_Ctl',
  siFile: 'infodoor',
  id: 1,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Up_Bitmap',
      siFile: 'infodoor',
      id: 6,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [14.0, 150.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowL.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Down_Bitmap',
      siFile: 'infodoor',
      id: 7,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [14.0, 150.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowLon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const RightArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'RightArrow_Ctl',
  siFile: 'infodoor',
  id: 2,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Up_Bitmap',
      siFile: 'infodoor',
      id: 8,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [581.0, 150.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowR.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Down_Bitmap',
      siFile: 'infodoor',
      id: 9,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [581.0, 150.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowRon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const Info_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Info_Ctl',
  siFile: 'infodoor',
  id: 3,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Info_Up_Bitmap',
      siFile: 'infodoor',
      id: 10,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [303.0, 108.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Info.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Info_Down_Bitmap',
      siFile: 'infodoor',
      id: 11,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [303.0, 108.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Infos.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const Door_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Door_Ctl',
  siFile: 'infodoor',
  id: 4,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Door_Up_Bitmap',
      siFile: 'infodoor',
      id: 12,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [227.0, 142.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Door.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const Background_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Background_Bitmap',
  siFile: 'infodoor',
  id: 5,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 10.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\backgrnd.bmp',
  fileType: 1280594720,
  extra: 'World:current',
  children: [],
} as const
export const LeftArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Up_Bitmap',
  siFile: 'infodoor',
  id: 6,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [14.0, 150.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowL.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const LeftArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Down_Bitmap',
  siFile: 'infodoor',
  id: 7,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [14.0, 150.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowLon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Up_Bitmap',
  siFile: 'infodoor',
  id: 8,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [581.0, 150.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowR.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Down_Bitmap',
  siFile: 'infodoor',
  id: 9,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [581.0, 150.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\arrowRon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const Info_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Info_Up_Bitmap',
  siFile: 'infodoor',
  id: 10,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [303.0, 108.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Info.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const Info_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Info_Down_Bitmap',
  siFile: 'infodoor',
  id: 11,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [303.0, 108.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Infos.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const Door_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Door_Up_Bitmap',
  siFile: 'infodoor',
  id: 12,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [227.0, 142.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Doors\\Door.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const ConfigAnimation = {
  type: Action.Type.ObjectAction,
  presenter: 'LegoAnimPresenter',
  name: 'ConfigAnimation',
  siFile: 'infodoor',
  id: 13,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\lego\\Media\\ani\\Worlds\\exitmain.ani',
  fileType: 1245859616,
  extra: null,
  children: [],
} as const
export const iic037in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iic037in_PlayWav',
  siFile: 'infodoor',
  id: 500,
  flags: 34,
  startTime: 0,
  duration: 11467,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iic037in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const iic038in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iic038in_PlayWav',
  siFile: 'infodoor',
  id: 501,
  flags: 34,
  startTime: 0,
  duration: 18391,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iic038in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const iicb31in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iicb31in_PlayWav',
  siFile: 'infodoor',
  id: 502,
  flags: 34,
  startTime: 0,
  duration: 13136,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iicb31in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const iic007in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iic007in_PlayWav',
  siFile: 'infodoor',
  id: 503,
  flags: 34,
  startTime: 0,
  duration: 15209,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iic007in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
