import { Action } from './types'
export const _StartUp = {
  type: Action.Type.ParallelAction,
  presenter: 'LegoWorldPresenter',
  name: '_StartUp',
  siFile: 'infoscor',
  id: 0,
  flags: 34,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Object:Score, World:ICUBE',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Background_Bitmap',
      siFile: 'infoscor',
      id: 11,
      flags: 34,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 10.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\backgrnd.bmp',
      fileType: 1280594720,
      extra: 'World:current',
      children: [],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'LeftArrow_Ctl',
      siFile: 'infoscor',
      id: 1,
      flags: 33,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Up_Bitmap',
          siFile: 'infoscor',
          id: 12,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [5.0, 290.0, 6.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowL.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LeftArrow_Down_Bitmap',
          siFile: 'infoscor',
          id: 13,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [5.0, 290.0, 6.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowLon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'RightArrow_Ctl',
      siFile: 'infoscor',
      id: 2,
      flags: 33,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Up_Bitmap',
          siFile: 'infoscor',
          id: 14,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [596.0, 278.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowR.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'RightArrow_Down_Bitmap',
          siFile: 'infoscor',
          id: 15,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [596.0, 278.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowRon.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Book_Ctl',
      siFile: 'infoscor',
      id: 3,
      flags: 33,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Book_Up_Bitmap',
          siFile: 'infoscor',
          id: 16,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [109.0, 102.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\Book.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'LegoBox_Ctl',
      siFile: 'infoscor',
      id: 4,
      flags: 33,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map;3;1;2;3, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'LegoBox_Mask_Bitmap',
          siFile: 'infoscor',
          id: 17,
          flags: 42,
          duration: 4294967295,
          loops: 1,
          location: [45.0, 228.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\boxmask.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ObjectAction,
      presenter: 'LegoAnimPresenter',
      name: 'ConfigAnimation',
      siFile: 'infoscor',
      id: 18,
      flags: 34,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\lego\\Media\\ani\\Worlds\\scormain.ani',
      fileType: 1245859616,
      extra: null,
      children: [],
    },
  ],
} as const
export const LeftArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'LeftArrow_Ctl',
  siFile: 'infoscor',
  id: 1,
  flags: 33,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Up_Bitmap',
      siFile: 'infoscor',
      id: 12,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [5.0, 290.0, 6.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowL.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LeftArrow_Down_Bitmap',
      siFile: 'infoscor',
      id: 13,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [5.0, 290.0, 6.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowLon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const RightArrow_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'RightArrow_Ctl',
  siFile: 'infoscor',
  id: 2,
  flags: 33,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Up_Bitmap',
      siFile: 'infoscor',
      id: 14,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [596.0, 278.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowR.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'RightArrow_Down_Bitmap',
      siFile: 'infoscor',
      id: 15,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [596.0, 278.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowRon.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const Book_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Book_Ctl',
  siFile: 'infoscor',
  id: 3,
  flags: 33,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Book_Up_Bitmap',
      siFile: 'infoscor',
      id: 16,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [109.0, 102.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\Book.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const LegoBox_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'LegoBox_Ctl',
  siFile: 'infoscor',
  id: 4,
  flags: 33,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map;3;1;2;3, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'LegoBox_Mask_Bitmap',
      siFile: 'infoscor',
      id: 17,
      flags: 42,
      duration: 4294967295,
      loops: 1,
      location: [45.0, 228.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\boxmask.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      children: [],
    },
  ],
} as const
export const HistBook_Bmp = {
  type: Action.Type.Still,
  presenter: null,
  name: 'HistBook_Bmp',
  siFile: 'infoscor',
  id: 5,
  flags: 34,
  duration: 4294967295,
  loops: 1,
  location: [70.0, 11.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\histbook.bmp',
  fileType: 1280594720,
  extra: 'World:current',
  children: [],
} as const
export const HistBook_Flc = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'HistBook_Flc',
  siFile: 'infoscor',
  id: 6,
  flags: 34,
  duration: 2100,
  loops: 1,
  location: [70.0, 11.0, 7.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\histbook.flc',
  fileType: 1129072160,
  extra: null,
  fps: 10,
  numFrames: 21,
  children: [],
} as const
export const LegoBox1_Flc = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'LegoBox1_Flc',
  siFile: 'infoscor',
  id: 7,
  flags: 34,
  duration: 9900,
  loops: 1,
  location: [0.0, 102.0, 7.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\box1.flc',
  fileType: 1129072160,
  extra: null,
  fps: 10,
  numFrames: 99,
  children: [],
} as const
export const LegoBox2_Flc = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'LegoBox2_Flc',
  siFile: 'infoscor',
  id: 8,
  flags: 34,
  duration: 22000,
  loops: 1,
  location: [0.0, 114.0, 7.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\box2.flc',
  fileType: 1129072160,
  extra: null,
  fps: 10,
  numFrames: 220,
  children: [],
} as const
export const LegoBox3_Flc = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'LegoBox3_Flc',
  siFile: 'infoscor',
  id: 9,
  flags: 34,
  duration: 12100,
  loops: 1,
  location: [0.0, 213.0, 7.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\box3.flc',
  fileType: 1129072160,
  extra: null,
  fps: 10,
  numFrames: 121,
  children: [],
} as const
export const GoTo_HistBook = {
  type: Action.Type.ParallelAction,
  presenter: null,
  name: 'GoTo_HistBook',
  siFile: 'infoscor',
  id: 10,
  flags: 34,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'HistBook_Bmp',
      siFile: 'infoscor',
      id: 5,
      flags: 34,
      duration: 4294967295,
      loops: 1,
      location: [70.0, 11.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\histbook.bmp',
      fileType: 1280594720,
      extra: 'World:current',
      children: [],
    },
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'HistBook_Flc',
      siFile: 'infoscor',
      id: 6,
      flags: 34,
      duration: 2100,
      loops: 1,
      location: [70.0, 11.0, 7.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\histbook.flc',
      fileType: 1129072160,
      extra: null,
      fps: 10,
      numFrames: 21,
      children: [],
    },
  ],
} as const
export const Background_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Background_Bitmap',
  siFile: 'infoscor',
  id: 11,
  flags: 34,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 10.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\backgrnd.bmp',
  fileType: 1280594720,
  extra: 'World:current',
  children: [],
} as const
export const LeftArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Up_Bitmap',
  siFile: 'infoscor',
  id: 12,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [5.0, 290.0, 6.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowL.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const LeftArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LeftArrow_Down_Bitmap',
  siFile: 'infoscor',
  id: 13,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [5.0, 290.0, 6.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowLon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Up_Bitmap',
  siFile: 'infoscor',
  id: 14,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [596.0, 278.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowR.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const RightArrow_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'RightArrow_Down_Bitmap',
  siFile: 'infoscor',
  id: 15,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [596.0, 278.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\arrowRon.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const Book_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Book_Up_Bitmap',
  siFile: 'infoscor',
  id: 16,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [109.0, 102.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Scripts\\Infocntr\\Floor1\\Score\\Book.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const LegoBox_Mask_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'LegoBox_Mask_Bitmap',
  siFile: 'infoscor',
  id: 17,
  flags: 42,
  duration: 4294967295,
  loops: 1,
  location: [45.0, 228.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scripts\\infocntr\\floor1\\score\\boxmask.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  children: [],
} as const
export const ConfigAnimation = {
  type: Action.Type.ObjectAction,
  presenter: 'LegoAnimPresenter',
  name: 'ConfigAnimation',
  siFile: 'infoscor',
  id: 18,
  flags: 34,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\lego\\Media\\ani\\Worlds\\scormain.ani',
  fileType: 1245859616,
  extra: null,
  children: [],
} as const
export const nin001pr_Anim = {
  type: Action.Type.ObjectAction,
  presenter: 'LegoLoopingAnimPresenter',
  name: 'nin001pr_Anim',
  siFile: 'infoscor',
  id: 19,
  flags: 34,
  duration: 4294967295,
  loops: 1,
  location: [8.504457473754883, 0.0, -0.0763079971075058],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\scene\\n\\in\\nin001pr.ani',
  fileType: 1245859616,
  extra: null,
  children: [],
} as const
export const nin001pr_RunAnim = {
  type: Action.Type.ParallelAction,
  presenter: null,
  name: 'nin001pr_RunAnim',
  siFile: 'infoscor',
  id: 500,
  flags: 34,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.ObjectAction,
      presenter: 'LegoLoopingAnimPresenter',
      name: 'nin001pr_Anim',
      siFile: 'infoscor',
      id: 19,
      flags: 34,
      duration: 4294967295,
      loops: 1,
      location: [8.504457473754883, 0.0, -0.0763079971075058],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\scene\\n\\in\\nin001pr.ani',
      fileType: 1245859616,
      extra: null,
      children: [],
    },
  ],
} as const
export const iicc31in_PlayWav = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'iicc31in_PlayWav',
  siFile: 'infoscor',
  id: 501,
  flags: 34,
  duration: 38048,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\audio\\offscreen\\in\\iicc31in.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
