import { Action } from './types'
export const Lego_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'Lego_Movie',
  siFile: 'intro',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'Lego_Smk',
      siFile: 'intro',
      id: 6,
      flags: 34,
      startTime: 0,
      duration: 14300,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\legomed.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'Lego_Wave',
      siFile: 'intro',
      id: 7,
      flags: 34,
      startTime: 0,
      duration: 14100,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\legomed.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const Mindscape_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'Mindscape_Movie',
  siFile: 'intro',
  id: 1,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'Mindscape_Smk',
      siFile: 'intro',
      id: 8,
      flags: 34,
      startTime: 0,
      duration: 11200,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\mindscap.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 640,
        height: 480,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'Mindscape_Wave',
      siFile: 'intro',
      id: 9,
      flags: 34,
      startTime: 0,
      duration: 8313,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\mindscap.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const Intro_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'Intro_Movie',
  siFile: 'intro',
  id: 2,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'Intro_Smk',
      siFile: 'intro',
      id: 10,
      flags: 34,
      startTime: 0,
      duration: 82000,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\intro.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'Intro_Wave',
      siFile: 'intro',
      id: 11,
      flags: 34,
      startTime: 0,
      duration: 82122,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\intro.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const Outro_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'Outro_Movie',
  siFile: 'intro',
  id: 3,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'Outro_Smk',
      siFile: 'intro',
      id: 12,
      flags: 34,
      startTime: 0,
      duration: 30000,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\Outro.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'Outro_Wave',
      siFile: 'intro',
      id: 13,
      flags: 34,
      startTime: 0,
      duration: 32829,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\Outro.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const BadEnd_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'BadEnd_Movie',
  siFile: 'intro',
  id: 4,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'BadEnd_Smk',
      siFile: 'intro',
      id: 14,
      flags: 34,
      startTime: 0,
      duration: 24700,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\BadEnd.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'BadEnd_Wave',
      siFile: 'intro',
      id: 15,
      flags: 34,
      startTime: 0,
      duration: 24700,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\BadEnd.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const GoodEnd_Movie = {
  type: Action.Type.ParallelAction,
  presenter: 'MxCompositeMediaPresenter',
  name: 'GoodEnd_Movie',
  siFile: 'intro',
  id: 5,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'GoodEnd_Smk',
      siFile: 'intro',
      id: 16,
      flags: 34,
      startTime: 0,
      duration: 104100,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\GoodEnd.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'GoodEnd_Wave',
      siFile: 'intro',
      id: 17,
      flags: 34,
      startTime: 0,
      duration: 104700,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\GoodEnd.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const Lego_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'Lego_Smk',
  siFile: 'intro',
  id: 6,
  flags: 34,
  startTime: 0,
  duration: 14300,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\legomed.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const Lego_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'Lego_Wave',
  siFile: 'intro',
  id: 7,
  flags: 34,
  startTime: 0,
  duration: 14100,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\legomed.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const Mindscape_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'Mindscape_Smk',
  siFile: 'intro',
  id: 8,
  flags: 34,
  startTime: 0,
  duration: 11200,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\mindscap.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 640,
    height: 480,
  },
  children: [],
} as const
export const Mindscape_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'Mindscape_Wave',
  siFile: 'intro',
  id: 9,
  flags: 34,
  startTime: 0,
  duration: 8313,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\mindscap.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const Intro_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'Intro_Smk',
  siFile: 'intro',
  id: 10,
  flags: 34,
  startTime: 0,
  duration: 82000,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\intro.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const Intro_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'Intro_Wave',
  siFile: 'intro',
  id: 11,
  flags: 34,
  startTime: 0,
  duration: 82122,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\intro.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const Outro_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'Outro_Smk',
  siFile: 'intro',
  id: 12,
  flags: 34,
  startTime: 0,
  duration: 30000,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\Outro.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const Outro_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'Outro_Wave',
  siFile: 'intro',
  id: 13,
  flags: 34,
  startTime: 0,
  duration: 32829,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\Outro.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const BadEnd_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'BadEnd_Smk',
  siFile: 'intro',
  id: 14,
  flags: 34,
  startTime: 0,
  duration: 24700,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\BadEnd.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const BadEnd_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'BadEnd_Wave',
  siFile: 'intro',
  id: 15,
  flags: 34,
  startTime: 0,
  duration: 24700,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\BadEnd.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
export const GoodEnd_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'GoodEnd_Smk',
  siFile: 'intro',
  id: 16,
  flags: 34,
  startTime: 0,
  duration: 104100,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\GoodEnd.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const GoodEnd_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'GoodEnd_Wave',
  siFile: 'intro',
  id: 17,
  flags: 34,
  startTime: 0,
  duration: 104700,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\GoodEnd.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
