import { Action } from './types'
export const _StartUp = {
  type: Action.Type.ParallelAction,
  presenter: 'LegoWorldPresenter',
  name: '_StartUp',
  siFile: 'jukeboxw',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Object:JukeBox',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Background_Bitmap',
      siFile: 'jukeboxw',
      id: 6,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [0.0, 0.0, 10.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\Media\\JukeBox\\backgrnd.bmp',
      fileType: 1280594720,
      extra: 'World:current',
      dimensions: {
        width: 640,
        height: 480,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Right_Bitmap',
      siFile: 'jukeboxw',
      id: 7,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [145.0, 20.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\Lego\\Media\\JukeBox\\Right.bmp',
      fileType: 1280594720,
      extra: 'Visibility:FALSE, World:current',
      dimensions: {
        width: 353,
        height: 332,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Decal_Bitmap',
      siFile: 'jukeboxw',
      id: 8,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [145.0, 20.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\Lego\\Media\\JukeBox\\Decal.bmp',
      fileType: 1280594720,
      extra: 'Visibility:FALSE, World:current',
      dimensions: {
        width: 353,
        height: 332,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Wallis_Bitmap',
      siFile: 'jukeboxw',
      id: 9,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [145.0, 20.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\Lego\\Media\\JukeBox\\Wallis.bmp',
      fileType: 1280594720,
      extra: 'Visibility:FALSE, World:current',
      dimensions: {
        width: 353,
        height: 332,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Nelson_Bitmap',
      siFile: 'jukeboxw',
      id: 10,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [145.0, 20.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\Lego\\Media\\JukeBox\\Nelson.bmp',
      fileType: 1280594720,
      extra: 'Visibility:FALSE, World:current',
      dimensions: {
        width: 353,
        height: 332,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Torpedos_Bitmap',
      siFile: 'jukeboxw',
      id: 11,
      flags: 34,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [145.0, 20.0, 8.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\Lego\\Media\\JukeBox\\Torpedos.bmp',
      fileType: 1280594720,
      extra: 'Visibility:FALSE, World:current',
      dimensions: {
        width: 353,
        height: 332,
      },
      children: [],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Voldown_Ctl',
      siFile: 'jukeboxw',
      id: 1,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Voldown_Up_Bitmap',
          siFile: 'jukeboxw',
          id: 12,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [32.0, 413.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\voldown.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 44,
            height: 54,
          },
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Voldown_Down_Bitmap',
          siFile: 'jukeboxw',
          id: 13,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [32.0, 413.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\voldownS.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 44,
            height: 54,
          },
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Volup_Ctl',
      siFile: 'jukeboxw',
      id: 2,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Volup_Up_Bitmap',
          siFile: 'jukeboxw',
          id: 14,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [558.0, 417.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\volup.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 44,
            height: 54,
          },
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Volup_Down_Bitmap',
          siFile: 'jukeboxw',
          id: 15,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [558.0, 417.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\volupS.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 44,
            height: 54,
          },
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Dback_Ctl',
      siFile: 'jukeboxw',
      id: 3,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Dback_Up_Bitmap',
          siFile: 'jukeboxw',
          id: 16,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [159.0, 422.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\dback.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 78,
            height: 41,
          },
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Dback_Down_Bitmap',
          siFile: 'jukeboxw',
          id: 17,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [159.0, 422.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\dbackS.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 78,
            height: 41,
          },
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Dfwd_Ctl',
      siFile: 'jukeboxw',
      id: 4,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Dfwd_Up_Bitmap',
          siFile: 'jukeboxw',
          id: 18,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [391.0, 422.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\dfwd.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 78,
            height: 41,
          },
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Dfwd_Down_Bitmap',
          siFile: 'jukeboxw',
          id: 19,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [391.0, 422.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\dfwdS.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 78,
            height: 41,
          },
          children: [],
        },
      ],
    },
    {
      type: Action.Type.ParallelAction,
      presenter: 'MxControlPresenter',
      name: 'Note_Ctl',
      siFile: 'jukeboxw',
      id: 5,
      flags: 33,
      startTime: 0,
      duration: 0,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      extra: 'Style:Map, World:current',
      children: [
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Note_Up_Bitmap',
          siFile: 'jukeboxw',
          id: 20,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [270.0, 420.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\note.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 86,
            height: 46,
          },
          children: [],
        },
        {
          type: Action.Type.Still,
          presenter: null,
          name: 'Note_Down_Bitmap',
          siFile: 'jukeboxw',
          id: 21,
          flags: 42,
          startTime: 0,
          duration: 4294967295,
          loops: 1,
          location: [270.0, 420.0, 9.0],
          direction: [0.0, 0.0, 1.0],
          up: [0.0, 1.0, 0.0],
          filename: 'Q:\\Lego\\media\\jukebox\\noteS.bmp',
          fileType: 1280594720,
          extra: 'BMP_ISMAP',
          dimensions: {
            width: 86,
            height: 46,
          },
          children: [],
        },
      ],
    },
  ],
} as const
export const Voldown_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Voldown_Ctl',
  siFile: 'jukeboxw',
  id: 1,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Voldown_Up_Bitmap',
      siFile: 'jukeboxw',
      id: 12,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [32.0, 413.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\voldown.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 44,
        height: 54,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Voldown_Down_Bitmap',
      siFile: 'jukeboxw',
      id: 13,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [32.0, 413.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\voldownS.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 44,
        height: 54,
      },
      children: [],
    },
  ],
} as const
export const Volup_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Volup_Ctl',
  siFile: 'jukeboxw',
  id: 2,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Volup_Up_Bitmap',
      siFile: 'jukeboxw',
      id: 14,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [558.0, 417.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\volup.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 44,
        height: 54,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Volup_Down_Bitmap',
      siFile: 'jukeboxw',
      id: 15,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [558.0, 417.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\volupS.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 44,
        height: 54,
      },
      children: [],
    },
  ],
} as const
export const Dback_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Dback_Ctl',
  siFile: 'jukeboxw',
  id: 3,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Dback_Up_Bitmap',
      siFile: 'jukeboxw',
      id: 16,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [159.0, 422.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\dback.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 78,
        height: 41,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Dback_Down_Bitmap',
      siFile: 'jukeboxw',
      id: 17,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [159.0, 422.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\dbackS.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 78,
        height: 41,
      },
      children: [],
    },
  ],
} as const
export const Dfwd_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Dfwd_Ctl',
  siFile: 'jukeboxw',
  id: 4,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Dfwd_Up_Bitmap',
      siFile: 'jukeboxw',
      id: 18,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [391.0, 422.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\dfwd.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 78,
        height: 41,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Dfwd_Down_Bitmap',
      siFile: 'jukeboxw',
      id: 19,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [391.0, 422.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\dfwdS.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 78,
        height: 41,
      },
      children: [],
    },
  ],
} as const
export const Note_Ctl = {
  type: Action.Type.ParallelAction,
  presenter: 'MxControlPresenter',
  name: 'Note_Ctl',
  siFile: 'jukeboxw',
  id: 5,
  flags: 33,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: 'Style:Map, World:current',
  children: [
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Note_Up_Bitmap',
      siFile: 'jukeboxw',
      id: 20,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [270.0, 420.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\note.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 86,
        height: 46,
      },
      children: [],
    },
    {
      type: Action.Type.Still,
      presenter: null,
      name: 'Note_Down_Bitmap',
      siFile: 'jukeboxw',
      id: 21,
      flags: 42,
      startTime: 0,
      duration: 4294967295,
      loops: 1,
      location: [270.0, 420.0, 9.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'Q:\\Lego\\media\\jukebox\\noteS.bmp',
      fileType: 1280594720,
      extra: 'BMP_ISMAP',
      dimensions: {
        width: 86,
        height: 46,
      },
      children: [],
    },
  ],
} as const
export const Background_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Background_Bitmap',
  siFile: 'jukeboxw',
  id: 6,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [0.0, 0.0, 10.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\Media\\JukeBox\\backgrnd.bmp',
  fileType: 1280594720,
  extra: 'World:current',
  dimensions: {
    width: 640,
    height: 480,
  },
  children: [],
} as const
export const Right_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Right_Bitmap',
  siFile: 'jukeboxw',
  id: 7,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [145.0, 20.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\Lego\\Media\\JukeBox\\Right.bmp',
  fileType: 1280594720,
  extra: 'Visibility:FALSE, World:current',
  dimensions: {
    width: 353,
    height: 332,
  },
  children: [],
} as const
export const Decal_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Decal_Bitmap',
  siFile: 'jukeboxw',
  id: 8,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [145.0, 20.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\Lego\\Media\\JukeBox\\Decal.bmp',
  fileType: 1280594720,
  extra: 'Visibility:FALSE, World:current',
  dimensions: {
    width: 353,
    height: 332,
  },
  children: [],
} as const
export const Wallis_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Wallis_Bitmap',
  siFile: 'jukeboxw',
  id: 9,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [145.0, 20.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\Lego\\Media\\JukeBox\\Wallis.bmp',
  fileType: 1280594720,
  extra: 'Visibility:FALSE, World:current',
  dimensions: {
    width: 353,
    height: 332,
  },
  children: [],
} as const
export const Nelson_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Nelson_Bitmap',
  siFile: 'jukeboxw',
  id: 10,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [145.0, 20.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\Lego\\Media\\JukeBox\\Nelson.bmp',
  fileType: 1280594720,
  extra: 'Visibility:FALSE, World:current',
  dimensions: {
    width: 353,
    height: 332,
  },
  children: [],
} as const
export const Torpedos_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Torpedos_Bitmap',
  siFile: 'jukeboxw',
  id: 11,
  flags: 34,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [145.0, 20.0, 8.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\Lego\\Media\\JukeBox\\Torpedos.bmp',
  fileType: 1280594720,
  extra: 'Visibility:FALSE, World:current',
  dimensions: {
    width: 353,
    height: 332,
  },
  children: [],
} as const
export const Voldown_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Voldown_Up_Bitmap',
  siFile: 'jukeboxw',
  id: 12,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [32.0, 413.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\voldown.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 44,
    height: 54,
  },
  children: [],
} as const
export const Voldown_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Voldown_Down_Bitmap',
  siFile: 'jukeboxw',
  id: 13,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [32.0, 413.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\voldownS.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 44,
    height: 54,
  },
  children: [],
} as const
export const Volup_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Volup_Up_Bitmap',
  siFile: 'jukeboxw',
  id: 14,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [558.0, 417.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\volup.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 44,
    height: 54,
  },
  children: [],
} as const
export const Volup_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Volup_Down_Bitmap',
  siFile: 'jukeboxw',
  id: 15,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [558.0, 417.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\volupS.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 44,
    height: 54,
  },
  children: [],
} as const
export const Dback_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Dback_Up_Bitmap',
  siFile: 'jukeboxw',
  id: 16,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [159.0, 422.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\dback.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 78,
    height: 41,
  },
  children: [],
} as const
export const Dback_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Dback_Down_Bitmap',
  siFile: 'jukeboxw',
  id: 17,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [159.0, 422.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\dbackS.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 78,
    height: 41,
  },
  children: [],
} as const
export const Dfwd_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Dfwd_Up_Bitmap',
  siFile: 'jukeboxw',
  id: 18,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [391.0, 422.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\dfwd.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 78,
    height: 41,
  },
  children: [],
} as const
export const Dfwd_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Dfwd_Down_Bitmap',
  siFile: 'jukeboxw',
  id: 19,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [391.0, 422.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\dfwdS.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 78,
    height: 41,
  },
  children: [],
} as const
export const Note_Up_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Note_Up_Bitmap',
  siFile: 'jukeboxw',
  id: 20,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [270.0, 420.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\note.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 86,
    height: 46,
  },
  children: [],
} as const
export const Note_Down_Bitmap = {
  type: Action.Type.Still,
  presenter: null,
  name: 'Note_Down_Bitmap',
  siFile: 'jukeboxw',
  id: 21,
  flags: 42,
  startTime: 0,
  duration: 4294967295,
  loops: 1,
  location: [270.0, 420.0, 9.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'Q:\\Lego\\media\\jukebox\\noteS.bmp',
  fileType: 1280594720,
  extra: 'BMP_ISMAP',
  dimensions: {
    width: 86,
    height: 46,
  },
  children: [],
} as const
