import { Action } from './types'
export const NoCD_Movie = {
  type: Action.Type.ParallelAction,
  presenter: null,
  name: 'NoCD_Movie',
  siFile: 'nocd',
  id: 0,
  flags: 34,
  startTime: 0,
  duration: 0,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  extra: null,
  children: [
    {
      type: Action.Type.Anim,
      presenter: null,
      name: 'CDSpin1_Smk',
      siFile: 'nocd',
      id: 1,
      flags: 34,
      startTime: 0,
      duration: 3400,
      loops: 1,
      location: [0.0, 0.0, -10000.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\media\\movies\\CDSpin1.smk',
      fileType: 1263358752,
      extra: null,
      dimensions: {
        width: 320,
        height: 240,
      },
      children: [],
    },
    {
      type: Action.Type.Sound,
      presenter: null,
      name: 'Iicx62In_Wave',
      siFile: 'nocd',
      id: 2,
      flags: 34,
      startTime: 0,
      duration: 3415,
      loops: 1,
      location: [0.0, 0.0, 0.0],
      direction: [0.0, 0.0, 1.0],
      up: [0.0, 1.0, 0.0],
      filename: 'q:\\lego\\Audio\\Offscreen\\In\\Iicx62In.wav',
      fileType: 1447122720,
      volume: 79,
      extra: null,
      children: [],
    },
  ],
} as const
export const CDSpin1_Smk = {
  type: Action.Type.Anim,
  presenter: null,
  name: 'CDSpin1_Smk',
  siFile: 'nocd',
  id: 1,
  flags: 34,
  startTime: 0,
  duration: 3400,
  loops: 1,
  location: [0.0, 0.0, -10000.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\media\\movies\\CDSpin1.smk',
  fileType: 1263358752,
  extra: null,
  dimensions: {
    width: 320,
    height: 240,
  },
  children: [],
} as const
export const Iicx62In_Wave = {
  type: Action.Type.Sound,
  presenter: null,
  name: 'Iicx62In_Wave',
  siFile: 'nocd',
  id: 2,
  flags: 34,
  startTime: 0,
  duration: 3415,
  loops: 1,
  location: [0.0, 0.0, 0.0],
  direction: [0.0, 0.0, 1.0],
  up: [0.0, 1.0, 0.0],
  filename: 'q:\\lego\\Audio\\Offscreen\\In\\Iicx62In.wav',
  fileType: 1447122720,
  volume: 79,
  extra: null,
  children: [],
} as const
