import * as THREE from 'three'
import { Action } from '../../actions/types'
import { type FileActionBase, getExtraValue, isAnimationPresenter, modelPresenter } from '../action-types'
import { getSettings } from '../settings'

THREE.Cache.enabled = !import.meta.env.DEV

const hdFiles = new Set<string>([
  // spellchecker: disable
  'isle/250.avif',
  'isle/250.png',
  'isle/251.avif',
  'isle/251.png',
  'jukebox/0.m4a',
  'jukebox/1.m4a',
  'jukebox/11.m4a',
  'jukebox/12.m4a',
  'jukebox/13.m4a',
  'jukebox/3.m4a',
  'jukebox/4.m4a',
  'jukebox/5.m4a',
  'jukebox/55.m4a',
  'jukebox/56.m4a',
  'jukebox/57.m4a',
  'jukebox/58.m4a',
  'jukebox/59.m4a',
  'jukebox/6.m4a',
  'jukebox/60.m4a',
  'jukebox/8.m4a',
  'jukebox/9.m4a',
  'world/images/black.gif.avif',
  'world/images/black.gif.png',
  'world/images/bowtie.gif.avif',
  'world/images/bowtie.gif.png',
  'world/images/bth1chst.gif.avif',
  'world/images/bth1chst.gif.png',
  'world/images/bth2chst.gif.avif',
  'world/images/bth2chst.gif.png',
  'world/images/construct.gif.avif',
  'world/images/construct.gif.png',
  'world/images/copchest.gif.avif',
  'world/images/copchest.gif.png',
  'world/images/doctor.gif.avif',
  'world/images/doctor.gif.png',
  'world/images/dogface.gif.avif',
  'world/images/dogface.gif.png',
  'world/images/e.gif.avif',
  'world/images/e.gif.png',
  'world/images/flowers.gif.avif',
  'world/images/flowers.gif.png',
  'world/images/fruit.gif.avif',
  'world/images/fruit.gif.png',
  'world/images/g.gif.avif',
  'world/images/g.gif.png',
  'world/images/gdface.gif.avif',
  'world/images/gdface.gif.png',
  'world/images/infochst.gif.avif',
  'world/images/infochst.gif.png',
  'world/images/infoface.gif.avif',
  'world/images/infoface.gif.png',
  'world/images/l.gif.avif',
  'world/images/l.gif.png',
  'world/images/l6.gif.avif',
  'world/images/l6.gif.png',
  'world/images/mamachst.gif.avif',
  'world/images/mamachst.gif.png',
  'world/images/mamaface.gif.avif',
  'world/images/mamaface.gif.png',
  'world/images/mech.gif.avif',
  'world/images/mech.gif.png',
  'world/images/mustache.gif.avif',
  'world/images/mustache.gif.png',
  'world/images/nickchst.gif.avif',
  'world/images/nickchst.gif.png',
  'world/images/nickface.gif.avif',
  'world/images/nickface.gif.png',
  'world/images/norachst.gif.avif',
  'world/images/norachst.gif.png',
  'world/images/noraface.gif.avif',
  'world/images/noraface.gif.png',
  'world/images/o.gif.avif',
  'world/images/o.gif.png',
  'world/images/papachst.gif.avif',
  'world/images/papachst.gif.png',
  'world/images/papaface.gif.avif',
  'world/images/papaface.gif.png',
  'world/images/peprchst.gif.avif',
  'world/images/peprchst.gif.png',
  'world/images/peprface.gif.avif',
  'world/images/peprface.gif.png',
  'world/images/polkadot.gif.avif',
  'world/images/polkadot.gif.png',
  'world/images/postchst.gif.avif',
  'world/images/postchst.gif.png',
  'world/images/rac1chst.gif.avif',
  'world/images/rac1chst.gif.png',
  'world/images/rac2chst.gif.avif',
  'world/images/rac2chst.gif.png',
  'world/images/shftchst.gif.avif',
  'world/images/shftchst.gif.png',
  'world/images/shftface.gif.avif',
  'world/images/shftface.gif.png',
  'world/images/shftface2.gif.avif',
  'world/images/shftface2.gif.png',
  'world/images/smile.gif.avif',
  'world/images/smile.gif.png',
  'world/images/smileshd.gif.avif',
  'world/images/smileshd.gif.png',
  'world/images/unkchst.gif.avif',
  'world/images/unkchst.gif.png',
  'world/images/vest.gif.avif',
  'world/images/vest.gif.png',
  'world/images/woman.gif.avif',
  'world/images/woman.gif.png',
  'world/images/womanshd.gif.avif',
  'world/images/womanshd.gif.png',
  'world/model_textures/^cave_24x.gif.avif',
  'world/model_textures/^cave_24x.gif.png',
  'world/model_textures/^caverocx.gif.avif',
  'world/model_textures/^caverocx.gif.png',
  'world/model_textures/^caverokx.gif.avif',
  'world/model_textures/^caverokx.gif.png',
  'world/model_textures/^grassx.gif.avif',
  'world/model_textures/^grassx.gif.png',
  'world/model_textures/^mitesx.gif.avif',
  'world/model_textures/^mitesx.gif.png',
  'world/model_textures/^pebblesx.gif.avif',
  'world/model_textures/^pebblesx.gif.png',
  'world/model_textures/^rockx.gif.avif',
  'world/model_textures/^rockx.gif.png',
  'world/model_textures/^sandredx.gif.avif',
  'world/model_textures/^sandredx.gif.png',
  'world/model_textures/^water2x.gif.avif',
  'world/model_textures/^water2x.gif.png',
  'world/model_textures/bank01.gif.avif',
  'world/model_textures/bank01.gif.png',
  'world/model_textures/beach.gif.avif',
  'world/model_textures/beach.gif.png',
  'world/model_textures/brela_01.gif.avif',
  'world/model_textures/brela_01.gif.png',
  'world/model_textures/cave_24x.gif.avif',
  'world/model_textures/cave_24x.gif.png',
  'world/model_textures/caverocx.gif.avif',
  'world/model_textures/caverocx.gif.png',
  'world/model_textures/caverokx.gif.avif',
  'world/model_textures/caverokx.gif.png',
  'world/model_textures/cheker01.gif.avif',
  'world/model_textures/cheker01.gif.png',
  'world/model_textures/chjetl.gif.avif',
  'world/model_textures/chjetl.gif.png',
  'world/model_textures/chjetr.gif.avif',
  'world/model_textures/chjetr.gif.png',
  'world/model_textures/chwind.gif.avif',
  'world/model_textures/chwind.gif.png',
  'world/model_textures/dbfrfn.gif.avif',
  'world/model_textures/dbfrfn.gif.png',
  'world/model_textures/finish.gif.avif',
  'world/model_textures/finish.gif.png',
  'world/model_textures/gasroad.gif.avif',
  'world/model_textures/gasroad.gif.png',
  'world/model_textures/grassx.gif.avif',
  'world/model_textures/grassx.gif.png',
  'world/model_textures/jailpad.gif.avif',
  'world/model_textures/jailpad.gif.png',
  'world/model_textures/jfrnt.gif.avif',
  'world/model_textures/jfrnt.gif.png',
  'world/model_textures/jsfrnt.gif.avif',
  'world/model_textures/jsfrnt.gif.png',
  'world/model_textures/jsfrnt1.gif.avif',
  'world/model_textures/jsfrnt1.gif.png',
  'world/model_textures/jsfrnt3.gif.avif',
  'world/model_textures/jsfrnt3.gif.png',
  'world/model_textures/jsfrnt4.gif.avif',
  'world/model_textures/jsfrnt4.gif.png',
  'world/model_textures/jswnsh.gif.avif',
  'world/model_textures/jswnsh.gif.png',
  'world/model_textures/jswnsh1.gif.avif',
  'world/model_textures/jswnsh1.gif.png',
  'world/model_textures/jswnsh5.gif.avif',
  'world/model_textures/jswnsh5.gif.png',
  'world/model_textures/jswnsh6.gif.avif',
  'world/model_textures/jswnsh6.gif.png',
  'world/model_textures/medic01.gif.avif',
  'world/model_textures/medic01.gif.png',
  'world/model_textures/mitesx.gif.avif',
  'world/model_textures/mitesx.gif.png',
  'world/model_textures/nopizza.gif.avif',
  'world/model_textures/nopizza.gif.png',
  'world/model_textures/nwcurve.gif.avif',
  'world/model_textures/nwcurve.gif.png',
  'world/model_textures/octan01.gif.avif',
  'world/model_textures/octan01.gif.png',
  'world/model_textures/octsq01.gif.avif',
  'world/model_textures/octsq01.gif.png',
  'world/model_textures/pebblesx.gif.avif',
  'world/model_textures/pebblesx.gif.png',
  'world/model_textures/pianokys.gif.avif',
  'world/model_textures/pianokys.gif.png',
  'world/model_textures/pizcurve.gif.avif',
  'world/model_textures/pizcurve.gif.png',
  'world/model_textures/pizza.gif.avif',
  'world/model_textures/pizza.gif.png',
  'world/model_textures/pizza01.gif.avif',
  'world/model_textures/pizza01.gif.png',
  'world/model_textures/polbar01.gif.avif',
  'world/model_textures/polbar01.gif.png',
  'world/model_textures/polbar02.gif.avif',
  'world/model_textures/polbar02.gif.png',
  'world/model_textures/polbla01.gif.avif',
  'world/model_textures/polbla01.gif.png',
  'world/model_textures/polwhi01.gif.avif',
  'world/model_textures/polwhi01.gif.png',
  'world/model_textures/post.gif.avif',
  'world/model_textures/post.gif.png',
  'world/model_textures/question.gif.avif',
  'world/model_textures/question.gif.png',
  'world/model_textures/raddis01.gif.avif',
  'world/model_textures/raddis01.gif.png',
  'world/model_textures/rcback.gif.avif',
  'world/model_textures/rcback.gif.png',
  'world/model_textures/rcfrnt.gif.avif',
  'world/model_textures/rcfrnt.gif.png',
  'world/model_textures/rcfrnt5.gif.avif',
  'world/model_textures/rcfrnt5.gif.png',
  'world/model_textures/rcfrnt6.gif.avif',
  'world/model_textures/rcfrnt6.gif.png',
  'world/model_textures/rcfrnt7.gif.avif',
  'world/model_textures/rcfrnt7.gif.png',
  'world/model_textures/rcside1.gif.avif',
  'world/model_textures/rcside1.gif.png',
  'world/model_textures/rcside2.gif.avif',
  'world/model_textures/rcside2.gif.png',
  'world/model_textures/rcside3.gif.avif',
  'world/model_textures/rcside3.gif.png',
  'world/model_textures/rctail.gif.avif',
  'world/model_textures/rctail.gif.png',
  'world/model_textures/redskul.gif.avif',
  'world/model_textures/redskul.gif.png',
  'world/model_textures/relrel01.gif.avif',
  'world/model_textures/relrel01.gif.png',
  'world/model_textures/road1way.gif.avif',
  'world/model_textures/road1way.gif.png',
  'world/model_textures/road3wa2.gif.avif',
  'world/model_textures/road3wa2.gif.png',
  'world/model_textures/road3wa3.gif.avif',
  'world/model_textures/road3wa3.gif.png',
  'world/model_textures/road3way.gif.avif',
  'world/model_textures/road3way.gif.png',
  'world/model_textures/road4way.gif.avif',
  'world/model_textures/road4way.gif.png',
  'world/model_textures/roadstr8.gif.avif',
  'world/model_textures/roadstr8.gif.png',
  'world/model_textures/rock07.gif.avif',
  'world/model_textures/rock07.gif.png',
  'world/model_textures/rock08.gif.avif',
  'world/model_textures/rock08.gif.png',
  'world/model_textures/rockrd3b.gif.avif',
  'world/model_textures/rockrd3b.gif.png',
  'world/model_textures/rockx.gif.avif',
  'world/model_textures/rockx.gif.png',
  'world/model_textures/sandredx.gif.avif',
  'world/model_textures/sandredx.gif.png',
  'world/model_textures/se_curve.gif.avif',
  'world/model_textures/se_curve.gif.png',
  'world/model_textures/shldwn02.gif.avif',
  'world/model_textures/shldwn02.gif.png',
  'world/model_textures/skull.gif.avif',
  'world/model_textures/skull.gif.png',
  'world/model_textures/smile.gif.avif',
  'world/model_textures/smile.gif.png',
  'world/model_textures/supr2_01.gif.avif',
  'world/model_textures/supr2_01.gif.png',
  'world/model_textures/tightcrv.gif.avif',
  'world/model_textures/tightcrv.gif.png',
  'world/model_textures/towrtop.gif.avif',
  'world/model_textures/towrtop.gif.png',
  'world/model_textures/val_02.gif.avif',
  'world/model_textures/val_02.gif.png',
  'world/model_textures/w_curve.gif.avif',
  'world/model_textures/w_curve.gif.png',
  'world/model_textures/water2x.gif.avif',
  'world/model_textures/water2x.gif.png',
  'world/model_textures/wnbars.gif.avif',
  'world/model_textures/wnbars.gif.png',
  'world/part_textures/^rockx.gif.avif',
  'world/part_textures/^rockx.gif.png',
  'world/part_textures/chjetl.gif.avif',
  'world/part_textures/chjetl.gif.png',
  'world/part_textures/donut.gif.avif',
  'world/part_textures/donut.gif.png',
  'world/part_textures/post.gif.avif',
  'world/part_textures/post.gif.png',
  'world/part_textures/redskul.gif.avif',
  'world/part_textures/redskul.gif.png',
  'world/part_textures/rock.gif.avif',
  'world/part_textures/rock.gif.png',
  'world/part_textures/rock07.gif.avif',
  'world/part_textures/rock07.gif.png',
  'world/part_textures/rockx.gif.avif',
  'world/part_textures/rockx.gif.png',
  'world/part_textures/smileshd.gif.avif',
  'world/part_textures/smileshd.gif.png',

  // spellchecker: enable
])

export const manager = new THREE.LoadingManager()
const fileLoader = new THREE.FileLoader(manager)
fileLoader.setResponseType('arraybuffer')

let supportsAvif = false
const avifTestImage = new Image()
avifTestImage.src =
  'data:image/avif;base64,AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAADybWV0YQAAAAAAAAAoaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAGxpYmF2aWYAAAAADnBpdG0AAAAAAAEAAAAeaWxvYwAAAABEAAABAAEAAAABAAABGgAAAB0AAAAoaWluZgAAAAAAAQAAABppbmZlAgAAAAABAABhdjAxQ29sb3IAAAAAamlwcnAAAABLaXBjbwAAABRpc3BlAAAAAAAAAAIAAAACAAAAEHBpeGkAAAAAAwgICAAAAAxhdjFDgQ0MAAAAABNjb2xybmNseAACAAIAAYAAAAAXaXBtYQAAAAAAAAABAAEEAQKDBAAAACVtZGF0EgAKCBgANogQEAwgMg8f8D///8WfhwB8+ErK42A='
avifTestImage.onload = () => {
  supportsAvif = true
}

export const getFileUrl = (path: string) => {
  if (getSettings().graphics.hdTextures && hdFiles.has(path)) {
    return `hd/${path}`
  }
  return `org/${path}`
}

export const getFile = async (path: string): Promise<ArrayBuffer> => {
  const res = await fileLoader.loadAsync(path)
  if (!(res instanceof ArrayBuffer)) {
    throw new Error(`Failed to load ${path}`)
  }
  return res
}

const getExtension = (fileType: Action.FileType, presenter: string | null, extra: string | null) => {
  switch (presenter === 'LegoTexturePresenter' ? Action.FileType.STL : fileType) {
    case Action.FileType.SMK:
      return 'mp4'
    case Action.FileType.WAV:
      return 'm4a'
    case Action.FileType.OBJ:
      if (presenter == null) {
        throw new Error(`Presenter is null for file type: ${fileType}`)
      }
      if (isAnimationPresenter(presenter)) {
        return 'ani'
      }
      if (presenter === modelPresenter) {
        return 'mod'
      }
      return 'gph'
    case Action.FileType.STL:
      if (supportsAvif && getExtraValue({ extra }, 'BMP_ISMAP') == null) {
        return 'avif'
      }
      return 'png'
    case Action.FileType.FLC:
      return 'mp4'
  }

  throw new Error(`Unknown file type: ${fileType}`)
}

export const getActionFileUrl = (action: FileActionBase) => getFileUrl(`${action.siFile}/${action.id}.${getExtension(action.fileType, action.presenter, action.extra)}`)

export const getAction = async (action: FileActionBase): Promise<ArrayBuffer> => getFile(getActionFileUrl(action))
